setup.py
When trying to use a development snapshot of `mypy` (through `pip install git+https://github.com/python/mypy.git\#egg\=mypy`), the current `setup.py` is ignoring the existing `mypy` installation because it doesn't match `mypy-lang`, making such use impossible.
Apparently mypy's maintainers managed to get access to `mypy` in PyPI, and their `setup.py` now builds using this very name.
This fix consists of dropping the dependency on `mypy-lang` and adding a new one on `mypy` requiring version `0.470` or newer, which is the earliest version available on  PyPI for this newly named package.
=> Update dependency from mypy-lang to mypy

.travis.yml, pytest_mypy.py, setup.py, tox.ini
Unfortunately the target function does not have any docstring in mypy,
but it is typed as Optional[] which means the function should accept
None as a value. Doing so seems to suppress issues reported in #6.
Quick skim of the culprit PR in mypy
(https://github.com/python/mypy/pull/4396/files) shows the code really
counts with None being passed and adjusting appropriately, citing:
> If we were not given a flush_errors, we use one that will populate
> those fields for callers that want the traditional API.
=> Call mypy with newly added parameter `flush_errors`

.travis.yml, pytest_mypy.py, setup.py, tox.ini
Reverts dbader/pytest-mypy#7
#8 is better because we'll start using mypy's public API.
=> Revert "Call mypy with newly added parameter `flush_errors`"

.travis.yml, pytest_mypy.py, setup.py, tox.ini
Fixes #6 
> I think we should strongly discourage such use of interfaces internal to mypy. The only public APIs are the command line and the mypy.api module.
https://github.com/python/mypy/issues/4681#issuecomment-371037599
=> Only depend on mypy.api

pytest_mypy.py
Closes #4 
I tested with https://github.com/petr-muller/vtes.
Control:
```
(vtes-S40RGN8u) david@kahuna:~/Projects/vtes $ rm -rf .pytest_cache/ .mypy_cache/
(vtes-S40RGN8u) david@kahuna:~/Projects/vtes $ time (mypy . ; pytest)
========================================== test session starts ==========================================
platform linux -- Python 3.6.5rc1, pytest-3.4.2, py-1.5.2, pluggy-0.6.0
...
======================================= 52 passed in 9.40 seconds =======================================
real	0m11.420s
user	0m10.489s
sys	0m0.866s
```
Before:
```
(vtes-S40RGN8u) david@kahuna:~/Projects/vtes $ rm -rf .pytest_cache/ .mypy_cache/
(vtes-S40RGN8u) david@kahuna:~/Projects/vtes $ time pytest --mypy
========================================== test session starts …
```
=> Invoke mypy with --incremental

pytest_mypy.py
Fixes #14 
Before:
```
___________________________________________________  ____________________________________________________
tests/conftest.py:8: error: No library stub file for module 'pytest'
tests/conftest.py:8: note: (Stub files are from https://github.com/python/typeshed)
tests/conftest.py:10: error: Cannot find module named 'backlog'
tests/conftest.py:10: note: (Perhaps setting MYPYPATH or using the "--ignore-missing-imports" flag would help)
----------------------------------------- Captured stdout call ------------------------------------------
Running mypy on /home/david/Projects/backlog/tests/conftest.py
```
After:
```
________________________________________ mypy tests/conftest.py _________________________________________
tests/conftest.py:8: error: No library stub file for …
```
=> Define a header for the test report

changelog.md
This was missed, but it isn't a huge deal since the change log is not a release artifact.
=> Add an entry for 0.3.1 to the change log

setup.py
Fix #27 
In addition to fixing #27, this version should be pinned so that a downstream project pinned to a particular version of `pytest-mypy` can more easily get reproducible test runs (i.e. a run doesn't fail because a newer version of Mypy was released).
=> Restrict the version of mypy used by the plugin with Python 3.4

pytest_mypy.py
The 'mypy' marker was introduced in #18. However, pytest doesn't know
about it and emits a warning.
This commit registers the marker to remove the warning, as documented by
pytest upstream:
https://docs.pytest.org/en/latest/writing_plugins.html#registering-markers
Fixes #25
=> Register the custom marker

setup.py, tests/test_pytest_mypy.py, tox.ini
Resolve #27
- > [The pytest 4.6 series will be the last to support Python 2.7 and 3.4](https://docs.pytest.org/en/latest/py27-py34-deprecation.html)
- As of `mypy-0.700`,
> [You can no longer run mypy using Python 3.4, since Python 3.4 has reached its end of life. ](https://mypy-lang.blogspot.com/2019/04/mypy-0700-released-up-to-4x-faster.html)
- #27 appears to be a test issue only as the tests do not fail when `runpytest_subprocess` is used instead of just `runpytest`.
- After adding supported mypy versions to the Tox matrix, [the entire matrix cannot be tested by Travis before the build is killed](https://travis-ci.com/dmtucker/pytest-mypy/builds/114854010). To mitigate this, we can reduce default testing to key versions that theoretically should provide comparable coverage (assuming …
=> Test supported versions of mypy

README.rst, changelog.md, src/pytest_mypy.py, tests/test_pytest_mypy.py
Fix #21 
Resolve #20 
To test performance, I downloaded [`requests3`](https://github.com/kennethreitz/requests3/tree/40aaff930106a73c9e19d40ff675b2e8efd62810) and ran this script (on https://github.com/dbader/pytest-mypy/commit/11d6c23f661bb4725c627a9e0821c9d5a18aa25e):
``` bash
pytest_mypy="$HOME/Projects/pytest-mypy"
tox_env='py37-pytest4.6-mypy0.711'
branch='run-once'
run_test () {
log="$1"
cd ~/Projects/requests3
"$pytest_mypy/.tox/$tox_env/bin/pip" install rfc3986 trio h11 pyOpenSSL twisted . 1>/dev/null 2>&1
rm -rf .mypy_cache/
time "$pytest_mypy/.tox/$tox_env/bin/pytest" --mypy -m mypy 1>"$pytest_mypy/$log.log" 2>&1
}
cd "$pytest_mypy"
git checkout dbader/master
tox -e "$tox_env" -r 1>/dev/null 2>&1
run_test master
cd "$pytest_mypy"
git checkout "$branch"
tox -e "$tox_env" -r …
```
=> Call mypy once and parse its output

setup.py
This was noticed while trying to install the package using poetry and encountering an issue [like this](https://github.com/sdispater/poetry/issues/1238).
I've tested installing with this change and it doesn't have the infinite recursion issue.
=> Do not overlap python_version requirements - fix for poetry package manager

tox.ini
=> Pin attrs for Pytest 4.0 - 4.2 in tox.ini

src/pytest_mypy.py
With this change the output will be green if mypy exits with status 0. This way simply looking at the color you can see if everything is OK.
=> Make success message green instead of red.

src/pytest_mypy.py
Fix #58 
First, I attempted to fix `MypyItem.mypy_path`; however, Mypy wasn't very helpful, unfortunately.
The problem is that the code it uses to calculate the path it ultimately displays is neither conveniently grouped nor exposed in the public API. I got a copy-pasta solution working (though, it is not fully covered) in https://github.com/dbader/pytest-mypy/pull/59/commits/6464322611d0e5f0c1d71e80812bc803fe327027, but concerns about the maintenance burden of trying to re-create what Mypy does under-the-hood (especially if that ever changes incompatibly) begged for another solution.
The primary reason for `MypyItem.mypy_path` is to match the path found in Mypy output to the appropriate `MypyItem`. It is also used in `reportinfo`, which is meant to reflect the path from Mypy output (e.g. …
=> Remove MypyItem.mypy_path

tests/test_pytest_mypy.py, tox.ini
The expected error message for missing imports changed in mypy 0.750: https://github.com/python/mypy/pull/7698
=> Fix tests for mypy>=0.750

setup.py, src/pytest_mypy.py, tests/test_pytest_mypy.py, tox.ini
Resolve #72 
#41 changed the plugin significantly by calling `mypy` once per session on all `MypyItem`s instead of once per `MypyItem`. Unfortunately, that broke compatibility with `pytest-xdist` in 2 ways:
- It used `pytest_runtestloop`, which is [re-implemented by `pytest-xdist` workers](https://github.com/pytest-dev/pytest-xdist/blob/6fd5b56491ac30b47e31a98dd79f16e1e85ecf41/OVERVIEW.md).
- It didn't expect `terminal` could be `None`.
To remedy the latter, this moves `mypy` unmatched output and stderr reporting to `pytest_terminal_summary`. For the former, this combines the following recipes:
- ["Making session-scoped fixtures execute only once" from `pytest-xdist`](https://github.com/pytest-dev/pytest-xdist/blob/6fd5b56491ac30b47e31a98dd79f16e1e85ecf41/README.rst#making-session-scoped-f …
=> Add support for pytest-xdist

setup.py, src/pytest_mypy.py, tests/test_pytest_mypy.py, tox.ini
Resolve #74 
I started with #45 to ensure the effort @neozenith put into this work is acknowledged 😊 
The main concern with that PR was primarily the use of the private attribute `_nodeid` and secondarily a forced changed (to absolute paths) of the default node ID. This deals with those by using the `nodeid` kwarg to `pytest.Item` and re-creating a `MypyItem` that will have a name added to the node ID (basing off of the original `MypyItem`'s node ID).
The `nodeid` kwarg is not available until Pytest 3.5, so **this drops support for `pytest >= 2.8, < 3.5`**. That has the convenient side-effect of fixing #46 (again), which was reintroduced by the extra testing in #73.
Lastly, the new node ID name is configurable in the same manner as `mypy_argv`:
``` python
import mypy.version  # beware: …
```
=> Add a configurable name to MypyItem node IDs

.travis.yml
Travis CI no longer supports deployment with Python 3.4:
https://travis-ci.org/dbader/pytest-mypy/jobs/654157543#L788
=> Deploy from Travis CI with Python 3.8

src/pytest_mypy.py, tests/test_pytest_mypy.py, tox.ini
Fix #69 
From [the Mypy docs](https://mypy.readthedocs.io/en/latest/running_mypy.html#follow-imports),
> Mypy is designed to [doggedly follow all imports](https://mypy.readthedocs.io/en/latest/running_mypy.html#finding-imports), even if the imported module is not a file you explicitly wanted mypy to check.
This is problematic because, if `mypy` reports errors in a file `pytest` didn't collect, `pytest-mypy` has no `MypyItem` (now `MypyFileItem`) to match the errors to, and, if there are no other errors to report, the plugin may not force [the correct `pytest` exit status](https://docs.pytest.org/en/latest/reference.html#_pytest.config.ExitCode.TESTS_FAILED)!
To remedy that, this injects a new `MypyStatusItem` which just checks the `mypy` exit status and fails if it's nonzero. _This means …
=> Inject a test that checks the mypy exit status

src/pytest_mypy.py
Resolve #81 
I ran into https://github.com/pytest-dev/pytest/issues/6928 and found this advice particularly helpful:
> the structurally correct solution is to have a `File` that collects a `Item`
I implemented it by adapting the [example for specifying tests in Yaml files](https://docs.pytest.org/en/5.4.1/example/nonpython.html).
Notable effects include:
- `MypyFileItem` is no longer a `pytest.File`.
- `nodeid_name` can no longer be `None`.
=> Use Node.from_parent to instantiate MypyItems

src/pytest_mypy.py, tests/test_pytest_mypy.py
Previously the in [PEP 561](https://www.python.org/dev/peps/pep-0561/#partial-stub-packages) introduced .pyi stub files were ignored by `pytest-mypy`, in contrast with `mypy` itself which handles them just fine.
This pull requests addresses aforementioned issue.
See also: https://mypy.readthedocs.io/en/stable/stubs.html
=> Fix an issue where PEP 561 .pyi stub files are ignored

.github/workflows/validation.yml, .travis.yml, pyproject.toml, setup.py, tests/test_pytest_mypy.py, tox.ini
Close #46 
[py34 has reached EOL](https://devguide.python.org/devcycle/#end-of-life-branches), and [`tox-gh-actions` does not support it](https://github.com/ymyzk/tox-gh-actions/blob/4b51ab6879d90d78362b98b4fd118b79d6b57808/setup.cfg#L40).
Dropping support should not affect the vast majority of active users.
In the last 30 days, py34 accounted for only 0.003% of `pytest-mypy` downloads:
```
$ pypinfo pytest-mypy pyversion
Served from cache: False
Data processed: 117.47 GiB
Data billed: 117.47 GiB
Estimated cost: $0.58
| python_version | download_count |
| -------------- | -------------- |
| 3.7            |         56,011 |
| 3.8            |         18,070 |
| 3.6            |         15,508 |
| 3.9            |            678 |
| 3.5            |            324 |
| 3.10           | …
```
=> Drop py34, add GitHub Actions and a tox env for publishing

tests/test_pytest_mypy.py
I discovered this in a local branch that makes use of [Pytest's `ExitCode` structure](https://docs.pytest.org/en/5.0.0/reference.html#pytest-exitcode) in the tests:
```
------------------------------------------------ Captured stdout call ------------------------------------------------
running: /home/dtux/Projects/pytest-mypy/.tox/py38-pytest6.x-mypy0.7x/bin/python -mpytest --basetemp=/tmp/pytest-of-dtux/pytest-27/popen-gw4/test_mypy_indirect_inject0/runpytest-0 --mypy empty
in: /tmp/pytest-of-dtux/pytest-27/popen-gw4/test_mypy_indirect_inject0
============================= test session starts ==============================
platform linux -- Python 3.8.2, pytest-6.0.1, py-1.9.0, pluggy-0.13.1
Using --randomly-seed=1471697750
rootdir: …
```
=> Fix test_mypy_indirect_inject

src/pytest_mypy.py, tests/test_pytest_mypy.py
This adds a new plugin attribute (`file_error_formatter`) that defines a callable which is invoked when `mypy` finds errors in a file.
Here is an example (similar to the new test) of how it can be used to resolve #90 (cc: @markusschmaus, @jduprey):
``` python
import py
def custom_file_error_formatter(item, results, errors):
"""Include the file path before each reported error."""
return '\n'.join(
'{path}:{error}'.format(
path=py.path.local('.').bestrelpath(item.fspath),
error=error,
)   
for error in errors
)
def pytest_configure(config):
plugin = config.pluginmanager.getplugin('mypy')
plugin.file_error_formatter = custom_file_error_formatter
```
=> Enable custom error formatting

src/pytest_mypy.py, tests/test_pytest_mypy.py, tox.ini
Resolve #85 
This behaves much better.
- Using `--looponfail` should no longer crash or run duplicates.
- The status check can now be run by node ID on any file (though, it may not be a really _useful_ thing to do).
- **Injecting _just_ `MypyFileItem`s in a `pytest_collection_modifyitems` hook no longer implies a status check.**
If you want that, you need to inject a `MypyStatusItem` too.
- Likewise, the `MypyStatusItem` is now present in `items` in `pytest_collection_modifyitems`.
Remove it to ignore `mypy` errors in uncollected modules.
=> Stop injecting MypyStatusItem in pytest_collection_modifyitems to fix --looponfail

src/pytest_mypy.py, tests/test_pytest_mypy.py
Resolve #115 
- This partially works around https://github.com/pytest-dev/pytest/issues/8016 for 3.10 <= pytest < 6.0.
- It avoids #115, but we cannot prevent taking [a code path that only collects 1 `Item`](https://github.com/pytest-dev/pytest/blob/c934de6e1bb65ec99d3d35827ad56d9c6081f429/src/_pytest/main.py#L587).
- The workaround does not help with 6.0 <= pytest < 6.2 (because [an assertion](https://github.com/pytest-dev/pytest/blob/1142d138e3801372efabc1199290d6840a1ca8a2/src/_pytest/main.py#L777) fails first).
- The issue is truly fixed in pytest 6.2 (by https://github.com/pytest-dev/pytest/pull/8022).
=> Implement MypyItem.collect for pytest < 6.0

setup.py, src/pytest_mypy.py, tox.ini
- There is a product code improvement that can be made by requiring `pytest>=4.2`.
- Pytest 4.x is no longer supported (except `4.6.x`, which is community supported):
- A project that uses `pytest>=4.2,<4.6` would probably not have too hard a time upgrading to 4.6.
=> Drop support for pytest<4.6

src/pytest_mypy.py, tests/test_pytest_mypy.py
=> feat: Allow pytest-mypy to pass mypy custom config file via flag

src/pytest_mypy.py, tests/test_pytest_mypy.py, tox.ini
=> Add support for mypy-0.990

changelog.md, pyproject.toml, tox.ini
Resolve #147 
FWIW, the motivation for using `~=` in the `[build-system]` is so that the build for a given release continues to work even after backwards-incompatible changes to `setuptools`/etc. are published.
That said, the downstream has the option to downgrade if the build of an old release breaks, and loosening the pins can enable OS packagers who may not have access to PyPI / the pinned versions.
=> Update build & publish deps

tests/test_pytest_mypy.py
=> Add test_pyproject_toml

src/pytest_mypy.py, tests/test_pytest_mypy.py
=> Prevent AttributeError in pytest_terminal_summary

pyproject.toml
We don't need to capture the requirements of other projects. For example, if mypy 0.50 were to work on Python 3.11, we would support it because we have to support it on Python 3.7 anyways. Moreover, simplifying these pins does not forego the ability to require newer versions of mypy/pytest as older versions of Python become unsupported.
=> Simplify project dependencies

pyproject.toml
Related: https://github.com/pypa/sampleproject/issues/203
> It's already pulled in by `setuptools` automatically, when building wheels is requested from the frontend. If only sdists are being build, `pyproject.toml` shouldn't forcefully inject this dependency into the ephemeral build env.
=> Remove wheel as a build dependency
